<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $inputs = [
            [1, 'AF', 'Afghanistan', 93, '؋', 'Kabul', 'AFN', 'Asia', 'AS'],
            [2, 'AX', 'Aland Islands', 358, '€', 'Mariehamn', 'EUR', 'Europe', 'EU'],
            [3, 'AL', 'Albania', 355, 'Lek', 'Tirana', 'ALL', 'Europe', 'EU'],
            [4, 'DZ', 'Algeria', 213, 'دج', 'Algiers', 'DZD', 'Africa', 'AF'],
            [5, 'AS', 'American Samoa', 1684, '$', 'Pago Pago', 'USD', 'Oceania', 'OC'],
            [6, 'AD', 'Andorra', 376, '€', 'Andorra la Vella', 'EUR', 'Europe', 'EU'],
            [7, 'AO', 'Angola', 244, 'Kz', 'Luanda', 'AOA', 'Africa', 'AF'],
            [8, 'AI', 'Anguilla', 1264, '$', 'The Valley', 'XCD', 'North America', 'NA'],
            [9, 'AQ', 'Antarctica', 672, '$', 'Antarctica', 'AAD', 'Antarctica', 'AN'],
            [10, 'AG', 'Antigua and Barbuda', 1268, '$', 'St. John\'s', 'XCD', 'North America', 'NA'],
            [11, 'AR', 'Argentina', 54, '$', 'Buenos Aires', 'ARS', 'South America', 'SA'],
            [12, 'AM', 'Armenia', 374, '֏', 'Yerevan', 'AMD', 'Asia', 'AS'],
            [13, 'AW', 'Aruba', 297, 'ƒ', 'Oranjestad', 'AWG', 'North America', 'NA'],
            [14, 'AU', 'Australia', 61, '$', 'Canberra', 'AUD', 'Oceania', 'OC'],
            [15, 'AT', 'Austria', 43, '€', 'Vienna', 'EUR', 'Europe', 'EU'],
            [16, 'AZ', 'Azerbaijan', 994, 'm', 'Baku', 'AZN', 'Asia', 'AS'],
            [17, 'BS', 'Bahamas', 1242, 'B$', 'Nassau', 'BSD', 'North America', 'NA'],
            [18, 'BH', 'Bahrain', 973, '.د.ب', 'Manama', 'BHD', 'Asia', 'AS'],
            [19, 'BD', 'Bangladesh', 880, '৳', 'Dhaka', 'BDT', 'Asia', 'AS'],
            [20, 'BB', 'Barbados', 1246, 'Bds$', 'Bridgetown', 'BBD', 'North America', 'NA'],
            [21, 'BY', 'Belarus', 375, 'Br', 'Minsk', 'BYN', 'Europe', 'EU'],
            [22, 'BE', 'Belgium', 32, '€', 'Brussels', 'EUR', 'Europe', 'EU'],
            [23, 'BZ', 'Belize', 501, '$', 'Belmopan', 'BZD', 'North America', 'NA'],
            [24, 'BJ', 'Benin', 229, 'CFA', 'Porto-Novo', 'XOF', 'Africa', 'AF'],
            [25, 'BM', 'Bermuda', 1441, '$', 'Hamilton', 'BMD', 'North America', 'NA'],
            [26, 'BT', 'Bhutan', 975, 'Nu.', 'Thimphu', 'BTN', 'Asia', 'AS'],
            [27, 'BO', 'Bolivia', 591, 'Bs.', 'Sucre', 'BOB', 'South America', 'SA'],
            [28, 'BQ', 'Bonaire, Sint Eustatius and Saba', 599, '$', 'Kralendijk', 'USD', 'North America', 'NA'],
            [29, 'BA', 'Bosnia and Herzegovina', 387, 'KM', 'Sarajevo', 'BAM', 'Europe', 'EU'],
            [30, 'BW', 'Botswana', 267, 'P', 'Gaborone', 'BWP', 'Africa', 'AF'],
            [31, 'BV', 'Bouvet Island', 55, 'kr', '', 'NOK', 'Antarctica', 'AN'],
            [32, 'BR', 'Brazil', 55, 'R$', 'Brasilia', 'BRL', 'South America', 'SA'],
            [33, 'IO', 'British Indian Ocean Territory', 246, '$', 'Diego Garcia', 'USD', 'Asia', 'AS'],
            [34, 'BN', 'Brunei Darussalam', 673, 'B$', 'Bandar Seri Begawan', 'BND', 'Asia', 'AS'],
            [35, 'BG', 'Bulgaria', 359, 'Лв.', 'Sofia', 'BGN', 'Europe', 'EU'],
            [36, 'BF', 'Burkina Faso', 226, 'CFA', 'Ouagadougou', 'XOF', 'Africa', 'AF'],
            [37, 'BI', 'Burundi', 257, 'FBu', 'Bujumbura', 'BIF', 'Africa', 'AF'],
            [38, 'KH', 'Cambodia', 855, 'KHR', 'Phnom Penh', 'KHR', 'Asia', 'AS'],
            [39, 'CM', 'Cameroon', 237, 'FCFA', 'Yaounde', 'XAF', 'Africa', 'AF'],
            [40, 'CA', 'Canada', 1, '$', 'Ottawa', 'CAD', 'North America', 'NA'],
            [41, 'CV', 'Cape Verde', 238, '$', 'Praia', 'CVE', 'Africa', 'AF'],
            [42, 'KY', 'Cayman Islands', 1345, '$', 'George Town', 'KYD', 'North America', 'NA'],
            [43, 'CF', 'Central African Republic', 236, 'FCFA', 'Bangui', 'XAF', 'Africa', 'AF'],
            [44, 'TD', 'Chad', 235, 'FCFA', 'N\'Djamena', 'XAF', 'Africa', 'AF'],
            [45, 'CL', 'Chile', 56, '$', 'Santiago', 'CLP', 'South America', 'SA'],
            [46, 'CN', 'China', 86, '¥', 'Beijing', 'CNY', 'Asia', 'AS'],
            [47, 'CX', 'Christmas Island', 61, '$', 'Flying Fish Cove', 'AUD', 'Asia', 'AS'],
            [48, 'CC', 'Cocos (Keeling) Islands', 672, '$', 'West Island', 'AUD', 'Asia', 'AS'],
            [49, 'CO', 'Colombia', 57, '$', 'Bogota', 'COP', 'South America', 'SA'],
            [50, 'KM', 'Comoros', 269, 'CF', 'Moroni', 'KMF', 'Africa', 'AF'],
            [51, 'CG', 'Congo', 242, 'FC', 'Brazzaville', 'XAF', 'Africa', 'AF'],
            [52, 'CD', 'Congo, Democratic Republic of the Congo', 242, 'FC', 'Kinshasa', 'CDF', 'Africa', 'AF'],
            [53, 'CK', 'Cook Islands', 682, '$', 'Avarua', 'NZD', 'Oceania', 'OC'],
            [54, 'CR', 'Costa Rica', 506, '₡', 'San Jose', 'CRC', 'North America', 'NA'],
            [55, 'CI', 'Cote D\'Ivoire', 225, 'CFA', 'Yamoussoukro', 'XOF', 'Africa', 'AF'],
            [56, 'HR', 'Croatia', 385, 'kn', 'Zagreb', 'HRK', 'Europe', 'EU'],
            [57, 'CU', 'Cuba', 53, '$', 'Havana', 'CUP', 'North America', 'NA'],
            [58, 'CW', 'Curacao', 599, 'ƒ', 'Willemstad', 'ANG', 'North America', 'NA'],
            [59, 'CY', 'Cyprus', 357, '€', 'Nicosia', 'EUR', 'Asia', 'AS'],
            [60, 'CZ', 'Czech Republic', 420, 'Kč', 'Prague', 'CZK', 'Europe', 'EU'],
            [61, 'DK', 'Denmark', 45, 'Kr.', 'Copenhagen', 'DKK', 'Europe', 'EU'],
            [62, 'DJ', 'Djibouti', 253, 'Fdj', 'Djibouti', 'DJF', 'Africa', 'AF'],
            [63, 'DM', 'Dominica', 1767, '$', 'Roseau', 'XCD', 'North America', 'NA'],
            [64, 'DO', 'Dominican Republic', 1809, '$', 'Santo Domingo', 'DOP', 'North America', 'NA'],
            [65, 'EC', 'Ecuador', 593, '$', 'Quito', 'USD', 'South America', 'SA'],
            [66, 'EG', 'Egypt', 20, 'ج.م', 'Cairo', 'EGP', 'Africa', 'AF'],
            [67, 'SV', 'El Salvador', 503, '$', 'San Salvador', 'USD', 'North America', 'NA'],
            [68, 'GQ', 'Equatorial Guinea', 240, 'FCFA', 'Malabo', 'XAF', 'Africa', 'AF'],
            [69, 'ER', 'Eritrea', 291, 'Nfk', 'Asmara', 'ERN', 'Africa', 'AF'],
            [70, 'EE', 'Estonia', 372, '€', 'Tallinn', 'EUR', 'Europe', 'EU'],
            [71, 'ET', 'Ethiopia', 251, 'Nkf', 'Addis Ababa', 'ETB', 'Africa', 'AF'],
            [72, 'FK', 'Falkland Islands (Malvinas)', 500, '£', 'Stanley', 'FKP', 'South America', 'SA'],
            [73, 'FO', 'Faroe Islands', 298, 'Kr.', 'Torshavn', 'DKK', 'Europe', 'EU'],
            [74, 'FJ', 'Fiji', 679, 'FJ$', 'Suva', 'FJD', 'Oceania', 'OC'],
            [75, 'FI', 'Finland', 358, '€', 'Helsinki', 'EUR', 'Europe', 'EU'],
            [76, 'FR', 'France', 33, '€', 'Paris', 'EUR', 'Europe', 'EU'],
            [77, 'GF', 'French Guiana', 594, '€', 'Cayenne', 'EUR', 'South America', 'SA'],
            [78, 'PF', 'French Polynesia', 689, '₣', 'Papeete', 'XPF', 'Oceania', 'OC'],
            [79, 'TF', 'French Southern Territories', 262, '€', 'Port-aux-Francais', 'EUR', 'Antarctica', 'AN'],
            [80, 'GA', 'Gabon', 241, 'FCFA', 'Libreville', 'XAF', 'Africa', 'AF'],
            [81, 'GM', 'Gambia', 220, 'D', 'Banjul', 'GMD', 'Africa', 'AF'],
            [82, 'GE', 'Georgia', 995, 'ლ', 'Tbilisi', 'GEL', 'Asia', 'AS'],
            [83, 'DE', 'Germany', 49, '€', 'Berlin', 'EUR', 'Europe', 'EU'],
            [84, 'GH', 'Ghana', 233, 'GH₵', 'Accra', 'GHS', 'Africa', 'AF'],
            [85, 'GI', 'Gibraltar', 350, '£', 'Gibraltar', 'GIP', 'Europe', 'EU'],
            [86, 'GR', 'Greece', 30, '€', 'Athens', 'EUR', 'Europe', 'EU'],
            [87, 'GL', 'Greenland', 299, 'Kr.', 'Nuuk', 'DKK', 'North America', 'NA'],
            [88, 'GD', 'Grenada', 1473, '$', 'St. George\'s', 'XCD', 'North America', 'NA'],
            [89, 'GP', 'Guadeloupe', 590, '€', 'Basse-Terre', 'EUR', 'North America', 'NA'],
            [90, 'GU', 'Guam', 1671, '$', 'Hagatna', 'USD', 'Oceania', 'OC'],
            [91, 'GT', 'Guatemala', 502, 'Q', 'Guatemala City', 'GTQ', 'North America', 'NA'],
            [92, 'GG', 'Guernsey', 44, '£', 'St Peter Port', 'GBP', 'Europe', 'EU'],
            [93, 'GN', 'Guinea', 224, 'FG', 'Conakry', 'GNF', 'Africa', 'AF'],
            [94, 'GW', 'Guinea-Bissau', 245, 'CFA', 'Bissau', 'XOF', 'Africa', 'AF'],
            [95, 'GY', 'Guyana', 592, '$', 'Georgetown', 'GYD', 'South America', 'SA'],
            [96, 'HT', 'Haiti', 509, 'G', 'Port-au-Prince', 'HTG', 'North America', 'NA'],
            [97, 'HM', 'Heard Island and Mcdonald Islands', 0, '$', '', 'AUD', 'Antarctica', 'AN'],
            [98, 'VA', 'Holy See (Vatican City State)', 39, '€', 'Vatican City', 'EUR', 'Europe', 'EU'],
            [99, 'HN', 'Honduras', 504, 'L', 'Tegucigalpa', 'HNL', 'North America', 'NA'],
            [100, 'HK', 'Hong Kong', 852, '$', 'Hong Kong', 'HKD', 'Asia', 'AS'],
            [101, 'HU', 'Hungary', 36, 'Ft', 'Budapest', 'HUF', 'Europe', 'EU'],
            [102, 'IS', 'Iceland', 354, 'kr', 'Reykjavik', 'ISK', 'Europe', 'EU'],
            [103, 'IN', 'India', 91, '₹', 'New Delhi', 'INR', 'Asia', 'AS'],
            [104, 'ID', 'Indonesia', 62, 'Rp', 'Jakarta', 'IDR', 'Asia', 'AS'],
            [105, 'IR', 'Iran, Islamic Republic of', 98, '﷼', 'Tehran', 'IRR', 'Asia', 'AS'],
            [106, 'IQ', 'Iraq', 964, 'د.ع', 'Baghdad', 'IQD', 'Asia', 'AS'],
            [107, 'IE', 'Ireland', 353, '€', 'Dublin', 'EUR', 'Europe', 'EU'],
            [108, 'IM', 'Isle of Man', 44, '£', 'Douglas, Isle of Man', 'GBP', 'Europe', 'EU'],
            [109, 'IL', 'Israel', 972, '₪', 'Jerusalem', 'ILS', 'Asia', 'AS'],
            [110, 'IT', 'Italy', 39, '€', 'Rome', 'EUR', 'Europe', 'EU'],
            [111, 'JM', 'Jamaica', 1876, 'J$', 'Kingston', 'JMD', 'North America', 'NA'],
            [112, 'JP', 'Japan', 81, '¥', 'Tokyo', 'JPY', 'Asia', 'AS'],
            [113, 'JE', 'Jersey', 44, '£', 'Saint Helier', 'GBP', 'Europe', 'EU'],
            [114, 'JO', 'Jordan', 962, 'ا.د', 'Amman', 'JOD', 'Asia', 'AS'],
            [115, 'KZ', 'Kazakhstan', 7, 'лв', 'Astana', 'KZT', 'Asia', 'AS'],
            [116, 'KE', 'Kenya', 254, 'KSh', 'Nairobi', 'KES', 'Africa', 'AF'],
            [117, 'KI', 'Kiribati', 686, '$', 'Tarawa', 'AUD', 'Oceania', 'OC'],
            [118, 'KP', 'Korea, Democratic People\'s Republic of', 850, '₩', 'Pyongyang', 'KPW', 'Asia', 'AS'],
            [119, 'KR', 'Korea, Republic of', 82, '₩', 'Seoul', 'KRW', 'Asia', 'AS'],
            [120, 'XK', 'Kosovo', 383, '€', 'Pristina', 'EUR', 'Europe', 'EU'],
            [121, 'KW', 'Kuwait', 965, 'ك.د', 'Kuwait City', 'KWD', 'Asia', 'AS'],
            [122, 'KG', 'Kyrgyzstan', 996, 'лв', 'Bishkek', 'KGS', 'Asia', 'AS'],
            [123, 'LA', 'Lao People\'s Democratic Republic', 856, '₭', 'Vientiane', 'LAK', 'Asia', 'AS'],
            [124, 'LV', 'Latvia', 371, '€', 'Riga', 'EUR', 'Europe', 'EU'],
            [125, 'LB', 'Lebanon', 961, '£', 'Beirut', 'LBP', 'Asia', 'AS'],
            [126, 'LS', 'Lesotho', 266, 'L', 'Maseru', 'LSL', 'Africa', 'AF'],
            [127, 'LR', 'Liberia', 231, '$', 'Monrovia', 'LRD', 'Africa', 'AF'],
            [128, 'LY', 'Libyan Arab Jamahiriya', 218, 'د.ل', 'Tripolis', 'LYD', 'Africa', 'AF'],
            [129, 'LI', 'Liechtenstein', 423, 'CHf', 'Vaduz', 'CHF', 'Europe', 'EU'],
            [130, 'LT', 'Lithuania', 370, '€', 'Vilnius', 'EUR', 'Europe', 'EU'],
            [131, 'LU', 'Luxembourg', 352, '€', 'Luxembourg', 'EUR', 'Europe', 'EU'],
            [132, 'MO', 'Macao', 853, '$', 'Macao', 'MOP', 'Asia', 'AS'],
            [133, 'MK', 'Macedonia, the Former Yugoslav Republic of', 389, 'ден', 'Skopje', 'MKD', 'Europe', 'EU'],
            [134, 'MG', 'Madagascar', 261, 'Ar', 'Antananarivo', 'MGA', 'Africa', 'AF'],
            [135, 'MW', 'Malawi', 265, 'MK', 'Lilongwe', 'MWK', 'Africa', 'AF'],
            [136, 'MY', 'Malaysia', 60, 'RM', 'Kuala Lumpur', 'MYR', 'Asia', 'AS'],
            [137, 'MV', 'Maldives', 960, 'Rf', 'Male', 'MVR', 'Asia', 'AS'],
            [138, 'ML', 'Mali', 223, 'CFA', 'Bamako', 'XOF', 'Africa', 'AF'],
            [139, 'MT', 'Malta', 356, '€', 'Valletta', 'EUR', 'Europe', 'EU'],
            [140, 'MH', 'Marshall Islands', 692, '$', 'Majuro', 'USD', 'Oceania', 'OC'],
            [141, 'MQ', 'Martinique', 596, '€', 'Fort-de-France', 'EUR', 'North America', 'NA'],
            [142, 'MR', 'Mauritania', 222, 'MRU', 'Nouakchott', 'MRO', 'Africa', 'AF'],
            [143, 'MU', 'Mauritius', 230, '₨', 'Port Louis', 'MUR', 'Africa', 'AF'],
            [144, 'YT', 'Mayotte', 262, '€', 'Mamoudzou', 'EUR', 'Africa', 'AF'],
            [145, 'MX', 'Mexico', 52, '$', 'Mexico City', 'MXN', 'North America', 'NA'],
            [146, 'FM', 'Micronesia, Federated States of', 691, '$', 'Palikir', 'USD', 'Oceania', 'OC'],
            [147, 'MD', 'Moldova, Republic of', 373, 'L', 'Chisinau', 'MDL', 'Europe', 'EU'],
            [148, 'MC', 'Monaco', 377, '€', 'Monaco', 'EUR', 'Europe', 'EU'],
            [149, 'MN', 'Mongolia', 976, '₮', 'Ulan Bator', 'MNT', 'Asia', 'AS'],
            [150, 'ME', 'Montenegro', 382, '€', 'Podgorica', 'EUR', 'Europe', 'EU'],
            [151, 'MS', 'Montserrat', 1664, '$', 'Plymouth', 'XCD', 'North America', 'NA'],
            [152, 'MA', 'Morocco', 212, 'DH', 'Rabat', 'MAD', 'Africa', 'AF'],
            [153, 'MZ', 'Mozambique', 258, 'MT', 'Maputo', 'MZN', 'Africa', 'AF'],
            [154, 'MM', 'Myanmar', 95, 'K', 'Nay Pyi Taw', 'MMK', 'Asia', 'AS'],
            [155, 'NA', 'Namibia', 264, '$', 'Windhoek', 'NAD', 'Africa', 'AF'],
            [156, 'NR', 'Nauru', 674, '$', 'Yaren', 'AUD', 'Oceania', 'OC'],
            [157, 'NP', 'Nepal', 977, '₨', 'Kathmandu', 'NPR', 'Asia', 'AS'],
            [158, 'NL', 'Netherlands', 31, '€', 'Amsterdam', 'EUR', 'Europe', 'EU'],
            [159, 'AN', 'Netherlands Antilles', 599, 'NAf', 'Willemstad', 'ANG', 'North America', 'NA'],
            [160, 'NC', 'New Caledonia', 687, '₣', 'Noumea', 'XPF', 'Oceania', 'OC'],
            [161, 'NZ', 'New Zealand', 64, '$', 'Wellington', 'NZD', 'Oceania', 'OC'],
            [162, 'NI', 'Nicaragua', 505, 'C$', 'Managua', 'NIO', 'North America', 'NA'],
            [163, 'NE', 'Niger', 227, 'CFA', 'Niamey', 'XOF', 'Africa', 'AF'],
            [164, 'NG', 'Nigeria', 234, '₦', 'Abuja', 'NGN', 'Africa', 'AF'],
            [165, 'NU', 'Niue', 683, '$', 'Alofi', 'NZD', 'Oceania', 'OC'],
            [166, 'NF', 'Norfolk Island', 672, '$', 'Kingston', 'AUD', 'Oceania', 'OC'],
            [167, 'MP', 'Northern Mariana Islands', 1670, '$', 'Saipan', 'USD', 'Oceania', 'OC'],
            [168, 'NO', 'Norway', 47, 'kr', 'Oslo', 'NOK', 'Europe', 'EU'],
            [169, 'OM', 'Oman', 968, '.ع.ر', 'Muscat', 'OMR', 'Asia', 'AS'],
            [170, 'PK', 'Pakistan', 92, '₨', 'Islamabad', 'PKR', 'Asia', 'AS'],
            [171, 'PW', 'Palau', 680, '$', 'Melekeok', 'USD', 'Oceania', 'OC'],
            [172, 'PS', 'Palestinian Territory, Occupied', 970, '₪', 'East Jerusalem', 'ILS', 'Asia', 'AS'],
            [173, 'PA', 'Panama', 507, 'B/.', 'Panama City', 'PAB', 'North America', 'NA'],
            [174, 'PG', 'Papua New Guinea', 675, 'K', 'Port Moresby', 'PGK', 'Oceania', 'OC'],
            [175, 'PY', 'Paraguay', 595, '₲', 'Asuncion', 'PYG', 'South America', 'SA'],
            [176, 'PE', 'Peru', 51, 'S/.', 'Lima', 'PEN', 'South America', 'SA'],
            [177, 'PH', 'Philippines', 63, '₱', 'Manila', 'PHP', 'Asia', 'AS'],
            [178, 'PN', 'Pitcairn', 64, '$', 'Adamstown', 'NZD', 'Oceania', 'OC'],
            [179, 'PL', 'Poland', 48, 'zł', 'Warsaw', 'PLN', 'Europe', 'EU'],
            [180, 'PT', 'Portugal', 351, '€', 'Lisbon', 'EUR', 'Europe', 'EU'],
            [181, 'PR', 'Puerto Rico', 1787, '$', 'San Juan', 'USD', 'North America', 'NA'],
            [182, 'QA', 'Qatar', 974, 'ق.ر', 'Doha', 'QAR', 'Asia', 'AS'],
            [183, 'RE', 'Reunion', 262, '€', 'Saint-Denis', 'EUR', 'Africa', 'AF'],
            [184, 'RO', 'Romania', 40, 'lei', 'Bucharest', 'RON', 'Europe', 'EU'],
            [185, 'RU', 'Russian Federation', 7, '₽', 'Moscow', 'RUB', 'Asia', 'AS'],
            [186, 'RW', 'Rwanda', 250, 'FRw', 'Kigali', 'RWF', 'Africa', 'AF'],
            [187, 'BL', 'Saint Barthelemy', 590, '€', 'Gustavia', 'EUR', 'North America', 'NA'],
            [188, 'SH', 'Saint Helena', 290, '£', 'Jamestown', 'SHP', 'Africa', 'AF'],
            [189, 'KN', 'Saint Kitts and Nevis', 1869, '$', 'Basseterre', 'XCD', 'North America', 'NA'],
            [190, 'LC', 'Saint Lucia', 1758, '$', 'Castries', 'XCD', 'North America', 'NA'],
            [191, 'MF', 'Saint Martin', 590, '€', 'Marigot', 'EUR', 'North America', 'NA'],
            [192, 'PM', 'Saint Pierre and Miquelon', 508, '€', 'Saint-Pierre', 'EUR', 'North America', 'NA'],
            [193, 'VC', 'Saint Vincent and the Grenadines', 1784, '$', 'Kingstown', 'XCD', 'North America', 'NA'],
            [194, 'WS', 'Samoa', 684, 'SAT', 'Apia', 'WST', 'Oceania', 'OC'],
            [195, 'SM', 'San Marino', 378, '€', 'San Marino', 'EUR', 'Europe', 'EU'],
            [196, 'ST', 'Sao Tome and Principe', 239, 'Db', 'Sao Tome', 'STD', 'Africa', 'AF'],
            [197, 'SA', 'Saudi Arabia', 966, '﷼', 'Riyadh', 'SAR', 'Asia', 'AS'],
            [198, 'SN', 'Senegal', 221, 'CFA', 'Dakar', 'XOF', 'Africa', 'AF'],
            [199, 'RS', 'Serbia', 381, 'din', 'Belgrade', 'RSD', 'Europe', 'EU'],
            [200, 'CS', 'Serbia and Montenegro', 381, 'din', 'Belgrade', 'RSD', 'Europe', 'EU'],
            [201, 'SC', 'Seychelles', 248, 'SRe', 'Victoria', 'SCR', 'Africa', 'AF'],
            [202, 'SL', 'Sierra Leone', 232, 'Le', 'Freetown', 'SLL', 'Africa', 'AF'],
            [203, 'SG', 'Singapore', 65, '$', 'Singapur', 'SGD', 'Asia', 'AS'],
            [204, 'SX', 'Sint Maarten', 721, 'ƒ', 'Philipsburg', 'ANG', 'North America', 'NA'],
            [205, 'SK', 'Slovakia', 421, '€', 'Bratislava', 'EUR', 'Europe', 'EU'],
            [206, 'SI', 'Slovenia', 386, '€', 'Ljubljana', 'EUR', 'Europe', 'EU'],
            [207, 'SB', 'Solomon Islands', 677, 'Si$', 'Honiara', 'SBD', 'Oceania', 'OC'],
            [208, 'SO', 'Somalia', 252, 'Sh.so.', 'Mogadishu', 'SOS', 'Africa', 'AF'],
            [209, 'ZA', 'South Africa', 27, 'R', 'Pretoria', 'ZAR', 'Africa', 'AF'],
            [210, 'GS', 'South Georgia and the South Sandwich Islands', 500, '£', 'Grytviken', 'GBP', 'Antarctica', 'AN'],
            [211, 'SS', 'South Sudan', 211, '£', 'Juba', 'SSP', 'Africa', 'AF'],
            [212, 'ES', 'Spain', 34, '€', 'Madrid', 'EUR', 'Europe', 'EU'],
            [213, 'LK', 'Sri Lanka', 94, 'Rs', 'Colombo', 'LKR', 'Asia', 'AS'],
            [214, 'SD', 'Sudan', 249, '.س.ج', 'Khartoum', 'SDG', 'Africa', 'AF'],
            [215, 'SR', 'Suriname', 597, '$', 'Paramaribo', 'SRD', 'South America', 'SA'],
            [216, 'SJ', 'Svalbard and Jan Mayen', 47, 'kr', 'Longyearbyen', 'NOK', 'Europe', 'EU'],
            [217, 'SZ', 'Swaziland', 268, 'E', 'Mbabane', 'SZL', 'Africa', 'AF'],
            [218, 'SE', 'Sweden', 46, 'kr', 'Stockholm', 'SEK', 'Europe', 'EU'],
            [219, 'CH', 'Switzerland', 41, 'CHf', 'Berne', 'CHF', 'Europe', 'EU'],
            [220, 'SY', 'Syrian Arab Republic', 963, 'LS', 'Damascus', 'SYP', 'Asia', 'AS'],
            [221, 'TW', 'Taiwan, Province of China', 886, '$', 'Taipei', 'TWD', 'Asia', 'AS'],
            [222, 'TJ', 'Tajikistan', 992, 'SM', 'Dushanbe', 'TJS', 'Asia', 'AS'],
            [223, 'TZ', 'Tanzania, United Republic of', 255, 'TSh', 'Dodoma', 'TZS', 'Africa', 'AF'],
            [224, 'TH', 'Thailand', 66, '฿', 'Bangkok', 'THB', 'Asia', 'AS'],
            [225, 'TL', 'Timor-Leste', 670, '$', 'Dili', 'USD', 'Asia', 'AS'],
            [226, 'TG', 'Togo', 228, 'CFA', 'Lome', 'XOF', 'Africa', 'AF'],
            [227, 'TK', 'Tokelau', 690, '$', '', 'NZD', 'Oceania', 'OC'],
            [228, 'TO', 'Tonga', 676, '$', 'Nuku\'alofa', 'TOP', 'Oceania', 'OC'],
            [229, 'TT', 'Trinidad and Tobago', 1868, '$', 'Port of Spain', 'TTD', 'North America', 'NA'],
            [230, 'TN', 'Tunisia', 216, 'ت.د', 'Tunis', 'TND', 'Africa', 'AF'],
            [231, 'TR', 'Turkey', 90, '₺', 'Ankara', 'TRY', 'Asia', 'AS'],
            [232, 'TM', 'Turkmenistan', 7370, 'T', 'Ashgabat', 'TMT', 'Asia', 'AS'],
            [233, 'TC', 'Turks and Caicos Islands', 1649, '$', 'Cockburn Town', 'USD', 'North America', 'NA'],
            [234, 'TV', 'Tuvalu', 688, '$', 'Funafuti', 'AUD', 'Oceania', 'OC'],
            [235, 'UG', 'Uganda', 256, 'USh', 'Kampala', 'UGX', 'Africa', 'AF'],
            [236, 'UA', 'Ukraine', 380, '₴', 'Kiev', 'UAH', 'Europe', 'EU'],
            [237, 'AE', 'United Arab Emirates', 971, 'إ.د', 'Abu Dhabi', 'AED', 'Asia', 'AS'],
            [238, 'GB', 'United Kingdom', 44, '£', 'London', 'GBP', 'Europe', 'EU'],
            [239, 'US', 'United States', 1, '$', 'Washington', 'USD', 'North America', 'NA'],
            [240, 'UM', 'United States Minor Outlying Islands', 1, '$', '', 'USD', 'North America', 'NA'],
            [241, 'UY', 'Uruguay', 598, '$', 'Montevideo', 'UYU', 'South America', 'SA'],
            [242, 'UZ', 'Uzbekistan', 998, 'лв', 'Tashkent', 'UZS', 'Asia', 'AS'],
            [243, 'VU', 'Vanuatu', 678, 'VT', 'Port Vila', 'VUV', 'Oceania', 'OC'],
            [244, 'VE', 'Venezuela', 58, 'Bs', 'Caracas', 'VEF', 'South America', 'SA'],
            [245, 'VN', 'Viet Nam', 84, '₫', 'Hanoi', 'VND', 'Asia', 'AS'],
            [246, 'VG', 'Virgin Islands, British', 1284, '$', 'Road Town', 'USD', 'North America', 'NA'],
            [247, 'VI', 'Virgin Islands, U.s.', 1340, '$', 'Charlotte Amalie', 'USD', 'North America', 'NA'],
            [248, 'WF', 'Wallis and Futuna', 681, '₣', 'Mata Utu', 'XPF', 'Oceania', 'OC'],
            [249, 'EH', 'Western Sahara', 212, 'MAD', 'El-Aaiun', 'MAD', 'Africa', 'AF'],
            [250, 'YE', 'Yemen', 967, '﷼', 'Sanaa', 'YER', 'Asia', 'AS'],
            [251, 'ZM', 'Zambia', 260, 'ZK', 'Lusaka', 'ZMW', 'Africa', 'AF'],
            [252, 'ZW', 'Zimbabwe', 263, '$', 'Harare', 'ZWL', 'Africa', 'AF'],
        ];

        foreach ($inputs as $data) {
            Country::insert([
                'id' => $data[0],
                'code' => $data[1],
                'name' => $data[2],
                'phone' => $data[3],
                'symbol' => $data[4],
                'capital' => $data[5],
                'currency' => $data[6],
                'continent' => $data[7],
                'continent_code' => $data[8],
            ]);
        }
    }
}
